---
- name: Fix Python import paths permanently
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure site-packages directory exists
      raw: |
        mkdir -p /usr/local/lib/python3.13/site-packages
        chmod 755 /usr/local/lib/python3.13/site-packages

    - name: Create .pth file using raw module
      raw: |
        cat > /usr/local/lib/python3.13/site-packages/ansible.pth <<EOF
        /usr/local/lib/python3.13/site-packages
        /usr/local/lib64/python3.13/site-packages
        EOF
        chmod 644 /usr/local/lib/python3.13/site-packages/ansible.pth

    - name: Verify Python paths
      raw: |
        python3 -c "import sys; print(sys.path)"
      register: python_paths
      changed_when: false

    - debug:
        var: python_paths.stdout_lines