---
- hosts: monitoring_servers
  become: yes
  tasks:
    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Start Grafana
      service:
        name: grafana
        state: started
        enabled: yes

    - name: Add Prometheus datasource (via API)
      uri:
        url: http://localhost:3000/api/datasources
        method: POST
        body_format: json
        body:
          name: "Prometheus"
          type: "prometheus"
          url: "http://localhost:9090"
          access: "proxy"
        status_code: 200
        headers:
          Content-Type: "application/json"
          Authorization: "Basic {{ 'admin:admin' | b64encode }}"