---
- hosts: monitoring_servers
  become: yes
  vars:
    grafana_version: "10.4.2"
    grafana_admin_password: "flask123"  # Change this!

  tasks:
    - name: Install prerequisites
      dnf:
        name: [wget]
        state: present
        update_cache: yes

    - name: Add Grafana repository
      yum_repository:
        name: grafana
        description: Grafana repository
        baseurl: https://packages.grafana.com/oss/rpm
        repo_gpgcheck: yes
        gpgcheck: yes
        enabled: yes
        gpgkey: https://packages.grafana.com/gpg.key
        sslverify: yes
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt

    - name: Install Grafana
      dnf:
        name: grafana
        state: present
        enablerepo: grafana
        update_cache: yes

    - name: Configure Grafana (basic settings)
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: "^admin_password ="
        line: "admin_password = {{ grafana_admin_password }}"
        state: present
      no_log: true  # Hides password from logs
      notify: restart grafana

    - name: Create data directory
      file:
        path: /var/lib/grafana
        state: directory
        owner: grafana
        group: grafana
        mode: '0750'

    - name: Ensure Grafana service is running
      systemd:
        name: grafana-server
        state: started
        enabled: yes

  handlers:
    - name: restart grafana
      systemd:
        name: grafana-server
        state: restarted
        daemon_reload: yes