---
- hosts: monitoring_servers
  become: yes
  vars:
    prometheus_version: "2.47.0"
    prometheus_arch: "linux-amd64"
  
  tasks:
    - name: Install prerequisites
      dnf:
        name: ["wget", "tar"]
        state: present
        update_cache: yes

    - name: Create prometheus user
      user:
        name: prometheus
        system: yes
        shell: /usr/sbin/nologin

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}.tar.gz"
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.{{ prometheus_arch }}/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        remote_src: yes
      loop:
        - prometheus
        - promtool

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Install systemd service file
      copy:
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
              --config.file=/etc/prometheus/prometheus.yml \
              --storage.tsdb.path=/var/lib/prometheus/ \
              --web.console.templates=/etc/prometheus/consoles \
              --web.console.libraries=/etc/prometheus/console_libraries
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/prometheus.service"
        mode: '0644'
      notify: reload systemd and start prometheus

    - name: Configure Prometheus
      copy:
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'flask-app'
              static_configs:
                - targets: ['{{ groups.flask_servers | map('extract', hostvars, ['ansible_host']) | list | join(':8000,') }}:8000']
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
      notify: reload systemd and start prometheus

  handlers:
    - name: reload systemd and start prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
        daemon_reload: yes