---
- hosts: monitoring_servers
  become: yes
  tasks:
    - name: Install prerequisites
      dnf:
        name: ["wget", "tar"]
        state: present
        update_cache: yes

    - name: Download Prometheus
      ansible.builtin.get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Extract Prometheus
      ansible.builtin.unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Install Prometheus binaries
      ansible.builtin.copy:
        src: "/tmp/prometheus-2.47.0.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: '0755'
        remote_src: yes  # This is the critical fix
      loop:
        - prometheus
        - promtool

    - name: Create Prometheus directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: Configure Prometheus
      ansible.builtin.copy:
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'flask-app'
              static_configs:
                - targets: ['{{ groups.flask_servers | map('extract', hostvars, ['ansible_host']) | list | join(':8000,') }}:8000']
        dest: /etc/prometheus/prometheus.yml
      notify: restart prometheus

  handlers:
    - name: restart prometheus
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
        enabled: yes
        daemon_reload: yes