---
- name: Fedora/Cloud Image Python Fix
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Reconfigure Python package structure
      raw: |
        # Fix for Fedora's split paths
        sudo ln -sf /usr/local/lib/python3.13/site-packages /usr/lib/python3.13/site-packages
        sudo ln -sf /usr/local/lib64/python3.13/site-packages /usr/lib64/python3.13/site-packages
        
        # Refresh Python cache
        sudo python3 -c "import importlib; importlib.invalidate_caches()"
        
        # Verify fix
        python3 -c "import sys; print('\n'.join(sys.path)); \
                   from ansible.module_utils.six.moves import urllib; \
                   print('IMPORT_SUCCESS')"
      register: fix_result
      ignore_errors: yes

    - debug:
        var: fix_result.stdout_lines