---
- name: Update apt packages
  apt:
    update_cache: yes
  become: yes

- name: Install Python3, pip, and venv
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: yes

- name: Install required Python packages
  pip:
        name:
          - six
          - ansible
        state: present

- name: Install Flask
  pip:
    name: flask
    executable: pip3
  become: yes
