---
# Phase 1: Critical System Setup
- name: Install Python and build tools (Fedora)
  ansible.builtin.command: |
    dnf install -y python3 python3-pip python3-devel gcc openssl-devel
  tags: always

# Phase 2: Fix Ansible environment
- name: Install ansible-core and six
  pip:
    name:
      - six>=1.16.0
      - ansible-core>=2.15
    executable: pip3

# Phase 3: Now safe to gather facts
- name: Enable fact gathering
  setup:

# Phase 4: Flask environment
- name: Install Flask stack
  pip:
    name:
      - flask
      - gunicorn
      - psycopg2-binary  # If using PostgreSQL
    executable: pip3
