---
- name: Create Flask app directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: fedora
    group: fedora
    mode: '0755'
  become: yes
  loop:
    - /var/www/flask_app
    - /var/www/flask_app/templates
    - /var/www/flask_app/venv  # Directory for virtual environment

- name: Copy application files
  copy:
    src: "files/{{ item.src }}"
    dest: "/var/www/flask_app/{{ item.dest }}"
    owner: fedora
    group: fedora
    mode: '0755'
  become: yes
  loop:
    - { src: 'app.py', dest: 'app.py' }
    - { src: 'config.py', dest: 'config.py' }
    - { src: 'templates/index.html', dest: 'templates/index.html' }
    - { src: 'requirements.txt', dest: 'requirements.txt' }  # Ensure this exists

- name: Install Python3 and virtualenv packages
  dnf:
    name:
      - python3
      - python3-virtualenv
    state: present
  become: yes

- name: Create Python virtual environment
  command: "python3 -m venv /var/www/flask_app/venv"
  args:
    creates: "/var/www/flask_app/venv/bin/activate"  # Makes it idempotent
  become: yes
  become_user: fedora  # Important to create venv as the app user

- name: Install Python dependencies in virtualenv
  pip:
    requirements: /var/www/flask_app/requirements.txt
    virtualenv: /var/www/flask_app/venv
    virtualenv_command: python3 -m venv  # More reliable than virtualenv binary
  become: yes
  become_user: fedora  # Install packages as the app user

- name: Deploy systemd service file
  template:
    src: flask_app.service.j2
    dest: /etc/systemd/system/flask_app.service
    mode: '0644'
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: Ensure Flask app service is running
  systemd:
    name: flask_app
    state: restarted
    enabled: yes
  become: yes