---
- name: Install pip
  package:
    name: python3-pip
    state: present
  when: "'flask_servers' in group_names"

- name: Install Flask using pip
  pip:
    name: flask
  when: "'flask_servers' in group_names"

- name: Install Docker
  yum:
    name: docker
    state: present
  when: "'flask_servers' in group_names"

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  when: "'flask_servers' in group_names"

- name: Pull the latest Flask app image from Docker Hub
  command: "docker pull your-dockerhub-username/flask-app:latest"
  when: "'flask_servers' in group_names"

- name: Remove existing container (if running)
  command: "docker rm -f flask-container"
  ignore_errors: yes
  when: "'flask_servers' in group_names"

- name: Run Flask container
  command: >
    docker run -d --name flask-container -p 5000:5000
    -e DB_HOST={{ hostvars[groups['dbserver'][0]]['ansible_host'] }}
    your-dockerhub-username/flask-app:latest
  when: "'flask_servers' in group_names"

