---
- name: Install required system packages
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Flask and dependencies
  pip:
    name:
      - flask
      - psycopg2
    state: present

- name: Ensure Flask app directory exists
  file:
    path: /home/ec2-user/flask_app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Download Flask app package from S3
  command: "aws s3 cp s3://your-jenkins-artifacts/{{ deploy_version }} /home/ec2-user/flask_app/flask-app.tar.gz"
  args:
    creates: /home/ec2-user/flask_app/flask-app.tar.gz

- name: Extract Flask app package
  unarchive:
    src: /home/ec2-user/flask_app/flask-app.tar.gz
    dest: /home/ec2-user/flask_app/
    remote_src: yes

- name: Set environment variables for PostgreSQL connection
  template:
    src: env.j2
    dest: /home/ec2-user/flask_app/.env
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Start Flask application
  shell: "nohup python3 /home/ec2-user/flask_app/app.py > /home/ec2-user/flask_app/app.log 2>&1 &"
  args:
    chdir: /home/ec2-user/flask_app
  async: 600
  poll: 0