---
- name: Deploy Flask application from S3
  hosts: all  # or your specific host group
  gather_facts: yes
  become: yes

  # Modern Ansible versions prefer this syntax for collections
  vars:
    app_version: "{{ app_version }}"
    s3_bucket: "{{ s3_bucket }}"
    s3_key: "{{ s3_key }}"
    app_path: "{{ app_path }}"

  tasks:
    - name: Ensure application directory exists
      ansible.builtin.file:
        path: "{{ app_path }}"
        state: directory
        mode: '0755'

    - name: Download application package from S3
      amazon.aws.aws_s3:
       bucket: "{{ s3_bucket }}"
       object: "{{ s3_key }}"
       dest: "/tmp/flask_app.tar.gz"
       mode: get

    - name: Extract application package
      ansible.builtin.unarchive:
        src: "/tmp/flask_app.tar.gz"
        dest: "{{ app_path }}"
        remote_src: yes