---
- name: Setup Flask App Servers
  hosts: flask_servers
  vars:
    ansible_python_interpreter: /usr/bin/python3.13
  gather_facts: no
  roles:
    - python_flask
    - deploy_app
    - configure_app

- name: Setup Database Server
  hosts: db_server
  roles:
    - postgresql


