---
- name: Fix Python import paths permanently
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Create .pth file for Python path
      copy:
        dest: /usr/local/lib/python3.13/site-packages/ansible.pth
        content: |
          /usr/local/lib/python3.13/site-packages
          /usr/local/lib64/python3.13/site-packages
        mode: 0644

    - name: Verify Python paths
      raw: |
        python3 -c "import sys; print(sys.path)"
      register: python_paths
      changed_when: false

    - debug:
        var: python_paths.stdout_lines